feat: Docker rootless (#451)
* feat: run in docker rootless environment

Modified vault compose entries to disable memory locking feature of vault. This lets us run vault in a rootless docker environment

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: expanded vault changes to remaining non taf compose files

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Added user ID resolver in Makefile and docker sock mounts for portainer and security-spire-config container

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

added user ID resolver in Makefile

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Added test for docker rootless mode in makefiles

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Fixed up left over lines

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Updated readme files

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: rootless docker

made makefile resolve docker environment

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: rootless docker

Updated compose files for root dir

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

added total system memory resolver to Makefile

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

added generated files

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Removed debug

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Fixed vault storage backend issue causing vault not to boot

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Commiting generated files

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: docker rootless

Fixed makefile delayed-start gen syntax issues

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: change yaml multi line Indicator

change yaml multi line Indicator

Signed-off-by: weichou1229 <weichou1229@gmail.com>

* feat: docker rootless

Removed multiline formatting

Signed-off-by: jakeiotechsys <jake@iotechsys.com>

* feat: add default vault config

add default vault config

Signed-off-by: weichou1229 <weichou1229@gmail.com>

---------

Signed-off-by: jakeiotechsys <jake@iotechsys.com>
Signed-off-by: weichou1229 <weichou1229@gmail.com>
Co-authored-by: weichou1229 <weichou1229@gmail.com>

diff --git a/compose-builder/Makefile b/compose-builder/Makefile
--- a/compose-builder/Makefile
+++ b/compose-builder/Makefile
@@ -36,6 +36,15 @@ BUS=
 NANOMQ=
 REGISTRY=
 
+# Resolve user ID for rootless docker port mapping
+export USERID:=$(shell id -u)
+
+# Set default rootful docker socket path
+export DOCKER_SOCKET_PATH=/var/run/docker.sock
+
+# Get total system memory in megabytes for vault config
+export TOTAL_SYSTEM_MEMORY:=$(shell grep MemTotal /proc/meminfo | awk '{print $$2}')m
+
 BROKER_YAML=add-mqtt-broker-mosquitto.yml
 TAF_BROKER_YAML=add-taf-mqtt-broker-mosquitto.yml
 
@@ -132,11 +141,19 @@ ifeq (keeper, $(filter keeper,$(ARGS)))
 	endif
 endif
 
-# When in delay-start mode, we have to make sure support serivces be delayed-start-compliant: i.e. the runtime-token configuration be added etc..
-ifeq (delayed-start, $(filter delayed-start,$(ARGS)))
-	ext_file_sup_notif:= $(shell ZERO_TRUST="$(MAKE_ZERO_TRUST)" GEN_EXT_DIR="$(GEN_EXT_DIR)" ./gen_runtime_token_config_compose_ext.sh support-notifications)
-	ext_file_sup_sch:= $(shell ZERO_TRUST="$(MAKE_ZERO_TRUST)" GEN_EXT_DIR="$(GEN_EXT_DIR)" ./gen_runtime_token_config_compose_ext.sh support-scheduler)
-	COMPOSE_FILES:=$(COMPOSE_FILES) -f $(ext_file_sup_notif) -f $(ext_file_sup_sch)
+# When in delay-start mode, ensure support services are delay-start-compliant by adding runtime-token configuration
+ifeq (delayed-start,$(filter delayed-start,$(ARGS)))
+    # Ensure Docker is running rootless, as security-spire-agent runs only in Docker rootless mode
+    ifneq (,$(wildcard /run/user/$(USERID)/docker.sock))
+        export DOCKER_SOCKET_PATH := /run/user/$(USERID)/docker.sock
+    endif
+
+    # Generate runtime token config for support services
+    ext_file_sup_notif := $(shell ZERO_TRUST="$(MAKE_ZERO_TRUST)" GEN_EXT_DIR="$(GEN_EXT_DIR)" ./gen_runtime_token_config_compose_ext.sh support-notifications)
+    ext_file_sup_sch := $(shell ZERO_TRUST="$(MAKE_ZERO_TRUST)" GEN_EXT_DIR="$(GEN_EXT_DIR)"  ./gen_runtime_token_config_compose_ext.sh support-scheduler)
+
+    # Add generated config files to COMPOSE_FILES
+    COMPOSE_FILES += -f $(ext_file_sup_notif) -f $(ext_file_sup_sch)
 endif
 
 # Add Device Services
@@ -1060,6 +1077,11 @@ help:
 	echo "See README.md in this folder"
 
 portainer:
+	@if [ ! -e /run/user/${USERID}/docker.sock ]; then \
+    	echo "Error: Docker socket not found at /run/user/${USERID}/docker.sock"; \
+    	echo "Please ensure Docker is running rootless."; \
+    	exit 1; \
+    fi
 	make -C ${RELEASE_FOLDER} portainer
 
 portainer-down:
